version: "3.7"
services:
  app:
    build:
      args:
        user: spacenews
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: space-news
    container_name: spacenewsapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - space-news

  nginx:
    image: nginx:alpine
    container_name: space-news-nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - space-news

networks:
  space-news:
    driver: bridge
